//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.7
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 60fd94b4-0944-49df-9529-327938cb5bb2 aws-my-sample-app-android-v0.7";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION = Regions.US_EAST_1;

    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID = "us-east-1:2fb30153-0f2b-4f60-bbd2-28d08efa98f2";

    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET = "spy-chat-bucket";

}
